server:
  port: ${PORT:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka}

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 2000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

market:
  bread:
    price: 3
  feign:
    bakery:
      name: bakery
      path: /bakery
