version: '2.1'

# check the env variables in .env

services:
  registry1:
    image: shuaicj/cloud-registry
    environment:
      HOSTNAME: registry1
      PORT: ${REGISTRY_PORT}
      REGISTRY_SERVICE_HA: "true"
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka
    expose:
      - ${REGISTRY_PORT}
    command: ["./start.sh"]

  registry2:
    image: shuaicj/cloud-registry
    environment:
      HOSTNAME: registry2
      PORT: ${REGISTRY_PORT}
      REGISTRY_SERVICE_HA: "true"
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka
    expose:
      - ${REGISTRY_PORT}
    command: ["./start.sh"]

  config:
    image: shuaicj/cloud-config
    environment:
      PORT: ${CONFIG_PORT}
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka
    expose:
      - ${CONFIG_PORT}
    command: ["./start-after-registry.sh", "registry1:${REGISTRY_PORT}", "registry2:${REGISTRY_PORT}"]

  gateway:
    image: shuaicj/cloud-gateway
    environment:
      PORT: ${GATEWAY_PORT}
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    expose:
      - ${GATEWAY_PORT}
    command: ["./start-after-config.sh", "registry1:${REGISTRY_PORT}", "registry2:${REGISTRY_PORT}"]

  service-a:
    image: shuaicj/cloud-service-a
    environment:
      PORT: ${SERVICE_A_PORT}
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka
    expose:
      - ${SERVICE_A_PORT}
    command: ["./start-after-config.sh", "registry1:${REGISTRY_PORT}", "registry2:${REGISTRY_PORT}"]

  service-b:
    image: shuaicj/cloud-service-b
    environment:
      PORT: ${SERVICE_B_PORT}
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka
    expose:
      - ${SERVICE_B_PORT}
    command: ["./start-after-config.sh", "registry1:${REGISTRY_PORT}", "registry2:${REGISTRY_PORT}"]

