version: '2.1'

# check the env variables in .env

services:
  config:
    image: shuaicj/cloud-config
    environment:
      PORT: ${CONFIG_PORT}
#    ports:
#      - ${CONFIG_PORT}:${CONFIG_PORT}
    expose:
      - ${CONFIG_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CONFIG_PORT}/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  registry1:
    image: shuaicj/cloud-registry
    environment:
      HOSTNAME: registry1
      PORT: ${REGISTRY_PORT}
      CONFIG_SERVICE_URL: http://config:${CONFIG_PORT}
      REGISTRY_SERVICE_HA: "true"
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka,http://registry3:${REGISTRY_PORT}/eureka
#    ports:
#      - ${REGISTRY_PORT}:${REGISTRY_PORT}
    expose:
      - ${REGISTRY_PORT}
    depends_on:
      config:
        condition: service_healthy

  registry2:
    image: shuaicj/cloud-registry
    environment:
      HOSTNAME: registry2
      PORT: ${REGISTRY_PORT}
      CONFIG_SERVICE_URL: http://config:${CONFIG_PORT}
      REGISTRY_SERVICE_HA: "true"
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka,http://registry3:${REGISTRY_PORT}/eureka
#    ports:
#      - ${REGISTRY_PORT}:${REGISTRY_PORT}
    expose:
      - ${REGISTRY_PORT}
    depends_on:
      config:
        condition: service_healthy

  registry3:
    image: shuaicj/cloud-registry
    environment:
      HOSTNAME: registry3
      PORT: ${REGISTRY_PORT}
      CONFIG_SERVICE_URL: http://config:${CONFIG_PORT}
      REGISTRY_SERVICE_HA: "true"
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka,http://registry3:${REGISTRY_PORT}/eureka
#    ports:
#      - ${REGISTRY_PORT}:${REGISTRY_PORT}
    expose:
      - ${REGISTRY_PORT}
    depends_on:
      config:
        condition: service_healthy

  gateway:
    image: shuaicj/cloud-gateway
    environment:
      PORT: ${GATEWAY_PORT}
      CONFIG_SERVICE_URL: http://config:${CONFIG_PORT}
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka,http://registry3:${REGISTRY_PORT}/eureka
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    expose:
      - ${GATEWAY_PORT}
    depends_on:
      config:
        condition: service_healthy

  bakery:
    image: shuaicj/cloud-service-bakery
    environment:
      PORT: ${BAKERY_PORT}
      CONFIG_SERVICE_URL: http://config:${CONFIG_PORT}
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka,http://registry3:${REGISTRY_PORT}/eureka
#    ports:
#      - ${BAKERY_PORT}:${BAKERY_PORT}
    expose:
      - ${BAKERY_PORT}
    depends_on:
      config:
        condition: service_healthy

  market:
    image: shuaicj/cloud-service-market
    environment:
      PORT: ${MARKET_PORT}
      CONFIG_SERVICE_URL: http://config:${CONFIG_PORT}
      REGISTRY_SERVICE_URL: http://registry1:${REGISTRY_PORT}/eureka,http://registry2:${REGISTRY_PORT}/eureka,http://registry3:${REGISTRY_PORT}/eureka
#    ports:
#      - ${MARKET_PORT}:${MARKET_PORT}
    expose:
      - ${MARKET_PORT}
    depends_on:
      config:
        condition: service_healthy
