apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-java
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
      - name: hello-java
        image: shuaicj/hello-docker
        ports:
        - name: http
          containerPort: 8080

