server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka}

zuul:
  routes:
    bakery:
      path: /bakery/**
      serviceId: bakery
      stripPrefix: false
