server:
  port: ${PORT:8082}
  contextPath: /market

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka}

market:
  bread:
    price: 3
  feign:
    bakery:
      name: bakery
      path: /bakery
